apiVersion: v1
kind: ServiceAccount
metadata:
  name: finetune
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role:finetune
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - 'patch'
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - inferenceservices
    verbs:
      - '*'
  - apiGroups:
      - serving.knative.dev
    resources:
      - services
      - revisions
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding:finetune-finetune
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role:finetune
subjects:
  - kind: ServiceAccount
    name: finetune
