apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  access_key: VTYyRVFTU0o3MlE5VDlMOVpGMTY=
  secret_key: M0ppZHlISnBoN1lvQkZlc2QxYXNBT0d3WVpaOTRjQVhtUUNQMFpSSQ==
  host_url: b2JqZWN0LmxhczEuY29yZXdlYXZlLmNvbQ==
