apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: gpt-pvc
  annotations:
    serving.kubeflow.org/gke-accelerator: GeForce_GTX_1070_Ti
spec:
  default:
    predictor:
      parallelism: 1
      # Target concurrency of 4 active requests to each container
      minReplicas: 0 # Allow scale to zero
      maxReplicas: 30
      tensorflow:
        storageUri: pvc://model-storage/124M/ # The PVC and path inside the PVC to the model
        runtimeVersion: "1.14.0-gpu"
        resources:
          limits:
            cpu: 1.5
            memory: 8Gi
            nvidia.com/gpu: 1

    transformer:
      parallelism: 300
      minReplicas: 0
      maxReplicas: 2
      custom:
        container:
          image: coreweave/gpt-transformer:0.14 # Docker image of the code found in transformer/
          name: user-container
          resources:
            limits:
              cpu: 3
              memory: 1Gi
            requests:
              cpu: 1
              memory: 256Mi
