apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "imagenet-pytorchjob"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: navarrepratt/pytorch_dist_resnet50:14
              command:
                - "torchrun"
                - "--nproc_per_node=8"
                - "--nnodes=$(WORLD_SIZE)"
                - "--node_rank=$(RANK)"
                - "--master_addr=$(MASTER_ADDR)"
                - "--master_port=$(MASTER_PORT)"
                - "/opt/resnet50/src/resnet50.py"
                - "--backend"
                - "nccl"
                - "--log-dir"
                - "/mnt/pvc/pytorch/logs"
                - "--data-dir"
                - "/mnt/pvc/dataset/ILSVRC/Data/CLS-LOC"
                - "--model-dir"
                - "/mnt/pvc/pytorch/checkpoints"
                - "--epochs"
                - "10"
                - "--batch-size"
                - "256"
                - "--wandb-project"
                - "resnet50-imagenet-pytorch"
                - "--wandb-run"
                - "a40-16gpu"
              resources:  # Use the full node
                requests:
                  cpu: 90
                  memory: 700G
                  nvidia.com/gpu: 8
                limits:
                  cpu: 90
                  memory: 700G
                  nvidia.com/gpu: 8
              volumeMounts:
                - name: kubeflow-resnet50
                  mountPath: /mnt/pvc
                - name: dshm
                  mountPath: /dev/shm
              env:
                - name: WANDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wandb-token-secret
                      key: token
          volumes:
            - name: kubeflow-resnet50
              persistentVolumeClaim:
                claimName: kubeflow-resnet50
            - emptyDir:
                medium: Memory
              name: dshm
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: gpu.nvidia.com/model
                        operator: In
                        values:
                          - A40
                      - key: failure-domain.beta.kubernetes.io/region
                        operator: In
                        values:
                          - LAS1

    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: navarrepratt/pytorch_dist_resnet50:14
              command:
                - "torchrun"
                - "--nproc_per_node=8"  # Num GPUs per worker
                - "--nnodes=$(WORLD_SIZE)"
                - "--node_rank=$(RANK)"
                - "--master_addr=$(MASTER_ADDR)"
                - "--master_port=$(MASTER_PORT)"
                - "/opt/resnet50/src/resnet50.py"
                - "--backend"
                - "nccl"
                - "--log-dir"
                - "/mnt/pvc/pytorch/logs"
                - "--data-dir"
                - "/mnt/pvc/dataset/ILSVRC/Data/CLS-LOC"
                - "--model-dir"
                - "/mnt/pvc/pytorch/checkpoints"
                - "--epochs"
                - "10"
                - "--batch-size"
                - "256"
                - "--wandb-project"
                - "resnet50-imagenet-pytorch"
                - "--wandb-run"
                - "a40-16gpu"
              resources:  # Use the full node
                requests:
                  cpu: 90
                  memory: 700G
                  nvidia.com/gpu: 8
                limits:
                  cpu: 90
                  memory: 700G
                  nvidia.com/gpu: 8
              volumeMounts:
                - name: kubeflow-resnet50
                  mountPath: /mnt/pvc
                - name: dshm
                  mountPath: /dev/shm
              env:
                - name: WANDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wandb-token-secret
                      key: token
          volumes:
            - name: kubeflow-resnet50
              persistentVolumeClaim:
                claimName: kubeflow-resnet50
            - emptyDir:
                medium: Memory
              name: dshm
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: gpu.nvidia.com/model
                        operator: In
                        values:
                          - A40
                      - key: failure-domain.beta.kubernetes.io/region
                        operator: In
                        values:
                          - LAS1
