apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: example-vs
spec:
  region: ORD1
  os:
    type: linux
  resources:
    gpu:
      type: Quadro_RTX_4000
      count: 1
    cpu:
      count: 4
    memory: 16Gi
  storage:
    root:
      size: 40Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name: ubuntu2004-nvidia-465-19-01-1-docker-master-20211011-ord1
  # Change user name and pasword
  # User is on the sudoers list
  #  users:
  #    - username: SET YOUR USERNAME HERE
  #      password: SET YOUR PASSWORD HERE  
  # To use key-based authentication replace and uncomment ssh-rsa below with your public ssh key
  #  sshpublickey: |
  #    ssh-rsa AAAAB3NzaC1yc2EAAAA ... user@hostname
  network:
    public: true
    tcp:
      ports:
        - 22
        - 443
        - 60443
        - 4172
        - 3389
    udp:
      ports:
        - 4172
        - 3389
  cloudInit: |
    # Write a simple script
    write_files:
    - content: |
        #!/bin/bash
        echo "Hello world!"
      path: /home/myuser/script.sh
      permissions: '0744'
      owner: myuser:myuser
    # Update packages
    package_update: true
    # Install packages
    packages:
      - curl
      - git
    # Run additional commands
    runcmd:
      - [df, -h]
      - [git, version]
      - [curl, --version ]
      - [bash, /home/myuser/script.sh]
  initializeRunning: true
