---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vs-block-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: block-nvme-ord1
  volumeMode: Block
  resources:
    requests:
      storage: 20Gi
---
apiVersion: virtualservers.coreweave.com/v1alpha1
kind: VirtualServer
metadata:
  name: vs-ubuntu2004-block-pvc
spec:
  region: ORD1
  os:
    type: linux
  resources:
    gpu:
      type: Quadro_RTX_4000
      count: 1
    cpu:
      count: 3
    memory: 16Gi
  storage:
    root:
      size: 40Gi
      storageClassName: block-nvme-ord1
      source:
        pvc:
          namespace: vd-images
          name: ubuntu2004-nvidia-510-47-03-1-docker-master-20220421-ord1
    additionalDisks:
      - name: additional-block-volume
        spec:
          persistentVolumeClaim:
            claimName: vs-block-pvc
#  users:
#    - username: SET YOUR USERNAME HERE
#      password: SET YOUR PASSWORD HERE  
      # To use key-based authentication replace and uncomment ssh-rsa below with your public ssh key
      # sshpublickey: |
      #  ssh-rsa AAAAB3NzaC1yc2EAAAA ... user@hostname
  network:
    public: true
    tcp:
      ports:
        - 22
  cloudInit: |
    # The disk_setup directive instructs Cloud-init to partition a disk.
    disk_setup:
      /dev/vdb:
        table_type: gpt
        layout: True
        overwrite: False
    # fs_setup describes the how the file systems are supposed to look.
    fs_setup:
      - label: None
        filesystem: ext4
        device: /dev/vdb
        partition: 'auto'
    # 'mounts' contains a list of lists; the inner list are entries for an /etc/fstab line
    mounts:
     - [ vdb, /mnt/block-pvc, auto, "defaults" ]
  initializeRunning: true
