apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  annotations:
    serving.kubeflow.org/gke-accelerator: Tesla_V100_sxm
  labels:
    qos.coreweave.cloud/latency: low
  name: aitextgen
spec:
  default:
    predictor:
      maxReplicas: 10
      minReplicas: 3
      parallelism: 1
      custom:
        container:
          image: coreweave/aitextgen-model:11
          name: kfserving-container
          resources:
            limits:
              cpu: "3"
              memory: 18Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "1"
              memory: 10Gi
