apiVersion: batch/v1
kind: Job
metadata:
  name: model-download
spec:
  template:
    spec:
      containers:
      - name: model-downloader
        image: rtalaricw/model-download-gptj:v1.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: model-cache
            mountPath: /mnt
        resources:
          requests:
            cpu: 4
            memory: 8Gi 
          limits:
            cpu: 4
            memory: 8Gi 
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-storage
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - LAS1
              
      restartPolicy: Never
  backoffLimit: 1