apiVersion: v1
kind: Service
metadata:
  name: spark-jupyter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: notebook
      port: 8888
      protocol: TCP
    - name: spark-ui
      port: 4040
      protocol: TCP
    - name: blockmanager
      port: 7777
      protocol: TCP
    - name: driver
      port: 2222
      protocol: TCP
  selector:
    app.kubernetes.io/name: spark-jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-jupyter
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-jupyter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-jupyter
    spec:
      serviceAccountName: spark-sa
      containers:
        - name: jupyter
          image: jupyter/all-spark-notebook:python-3.10
          command:
            - "jupyter"
            - "lab"
            - "--ip"
            - "0.0.0.0"
            - "--no-browser"
            - "--allow-root"
            - "--notebook-dir"
            - "/mnt/pvc"
            - "--LabApp.token=''"

          securityContext:
            runAsUser: 0

          ports:
            - name: notebook
              containerPort: 8888
              protocol: TCP
            - name: blockmanager
              containerPort: 7777
              protocol: TCP
            - name: driver
              containerPort: 2222
              protocol: TCP
            - name: spark-ui
              containerPort: 4040
              protocol: TCP

          readinessProbe:
            tcpSocket:
              port: notebook
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: notebook
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 10

          volumeMounts:
            - name: storage
              mountPath: /mnt/pvc

          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-token-secret
                  key: token

          resources:
            requests:
              cpu: "4"
              memory: 16Gi
            limits:
              cpu: "4"
              memory: 16Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - "LGA1"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: spark-pvc
      restartPolicy: Always