apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sleep
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sleep
    spec:
      containers:
      - name: sleep
        image: banst/awscli:1.18.56
        # Simple way of keeping an idle container running
        command: [sleep]
        args: ["86400d"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 1
            memory: 128Mi
        volumeMounts:
          - name: model-storage
            mountPath: /models

      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - ORD1
