apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: clone-to-file
  name: clone-to-file
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: clone-to-file
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/region
                    operator: In
                    values:
                      - ORD1
                  - key: node.coreweave.cloud/class
                    operator: In
                    values:
                      - cpu
                  - key: ethernet.coreweave.cloud/speed
                    operator: In
                    values:
                      - 10G
                      - 40G
      containers:
        - name: clone-to-file
          resources:
            requests:
              cpu: 1
              memory: 2Gi
          image: registry.gitlab.com/coreweave/utility-images/admin-shell:36f48c0d
          command:
            - sh
            - '-c'
            - 'qemu-img convert -f raw -O qcow2 /dev/xvda /shared-data/disk.qcow2 -c -p'
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
          volumeDevices:
            - devicePath: /dev/xvda
              name: source
      restartPolicy: OnFailure
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
            readOnly: false
        - name: source
          persistentVolumeClaim:
            claimName: winserver2019std-clone-20210701-ord1
            readOnly: true
      tolerations:
        - key: node.coreweave.cloud/hypervisor
          operator: Exists
        - key: is_cpu_compute
          operator: Exists
