apiVersion: batch/v1
kind: Job
metadata:
  name: neox-checkpoint-download
spec:
  template:
    spec:
      containers:
        - name: checkpoint-downloader
          image: ghcr.io/coreweave/ml-containers/gpt-neox-mpi:npratt-gpt-neox-mpi-a5cccd0
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c" ]
          args:
            - dest=$(yq '.load' /mnt/config/neox.yml);
              url=$(cat /mnt/config/model_weights_url);
              mkdir -p $dest;
              wget --cut-dirs=5 -nH -r --no-parent --reject "index.html*" $url -P $dest
          volumeMounts:
            - name: neox-checkpoints
              mountPath: /mnt/checkpoints
            - mountPath: /mnt/config
              name: config
          resources:
            requests:
              cpu: "1"
              memory: 4Gi
            limits:
              cpu: "1"
              memory: 4Gi
      volumes:
        - name: neox-checkpoints
          persistentVolumeClaim:
            claimName: neox-checkpoints
        - name: config
          configMap:
            name: neox-training
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - LAS1
      restartPolicy: Never
  backoffLimit: 2
