apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-neox-dataset
spec:
  template:
    spec:
      containers:
        - name: prepare-neox-dataset
          image: ghcr.io/coreweave/ml-containers/gpt-neox-mpi:npratt-gpt-neox-mpi-a5cccd0
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c" ]
          args:
            - "python prepare_data.py \
              -d $(yq '.data-path' /mnt/config/neox.yml | rev | cut -d'/' -f3- | rev) \
              -t HFTokenizer \
              --vocab-file $(yq '.vocab-file' /mnt/config/neox.yml) \
              $(yq '.data-path' /mnt/config/neox.yml | rev | cut -d'/' -f2 | rev)"
          volumeMounts:
            - name: neox-data
              mountPath: /mnt/data
            - name: neox-checkpoints
              mountPath: /mnt/checkpoints
            - mountPath: /mnt/config
              name: config
          resources:
            requests:
              cpu: "8"
              memory: 16Gi
            limits:
              cpu: "8"
              memory: 16Gi
      volumes:
        - name: neox-data
          persistentVolumeClaim:
            claimName: neox-data
        - name: neox-checkpoints
          persistentVolumeClaim:
            claimName: neox-checkpoints
        - name: config
          configMap:
            name: neox-training
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - LAS1
      restartPolicy: Never
  backoffLimit: 2
