apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeflow-imagenet
spec:
  storageClassName: shared-hdd-las1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
