apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
spec:
  storageClassName: shared-nvme-las1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi