apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sshd-root-pv-claim
spec:
  # Available storage classes at time of writing are
  # block-nvme-ord1 - Chicago - NVMe Storage with 3 Replicas
  # block-hdd-ord1 - Chicago - HDD Storage with 3 Replicas
  # Other data centers currently available [ewr1, las1]
  storageClassName: block-nvme-ord1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
